### ISSUE TITLE
1. Setting a property: built-in methods vs constructor

### ISSUE THREAD

**Issue by mikibonacci** [aiidateam/aiida-atomistic#1]
## Using built-in methods:

The current implementation supports two ways to set a property, both via methods of the StructureData itself or of the property class:
```python=
### Store the Pbc property in a StructureData node.
##########################################################
#
#
structure = StructureData()
#
# (1) using the set_property method:
#
structure.set_property(name='pbc', value={'value':[True,False,True]})
#
# (2) using built-in method of Pbc property. 
#     This calls internally the set_property method.
#
structure.pbc.set_from_string(dimensionality="3D") 
# ==> structure.pbc.value is then [True,True,True]
#
#The built-in methods then should work in this way:
structure.pbc.set_pbc(input_list=[True,True,True],...)
structure.pbc.from_structure(structure=other_structure,...)
#
# We cannot do the following:
#
# A property should be  read-only if accessed directly:
structure.pbc.value = 54
structure.pbc = Pbc([True,False,True])



#
# Not possible to set unsupported properties or to provide random parameters
structure.set_property(name='unsupported', value={'value':5})
structure.set_property(name='pbc', value={'unsupported_params':5})
``` 
The built-in methods of the properties should call the `set_property` method in order to set/update the value of a property. This ensures consistency and data validation checks and also consistency for the usage of the StructureData in different plugins.

## Using a constructor

**However**, in this way the immutability of a property is less robust: we can always use one of the methods above to override a property at any time (of course, only if the node is not stored). This may also lead to some unconsistency with other properties which are already defined. A way to avoid these two issues is to delegate everything (StructureData and properties setting) to the constructor of the StructureData class:
```python=
### Store the Pbc property in a StructureData node.
##########################################################
#
#
pbc_3d = Pbc(value=[True,True,True])
spin_up = Magnetization(moments=[1,1,1,...])
...
#
structure = StructureData(pbc=pbc_3d, magnetization=spin_up, ...)
```
some advantages are: 
- concrete immutability: you have to create a new StructureData class to change a property - everything is really read-only;
- consistency checks at creation time
- can instantiate a property directly; more intuitive and flexible - at least before the StructureData node creation

A disadvantage that I see it is that structure dependent property that we may want to initialize are not straightforward: for example, [if we want to provide Hubbard U for a given set of atoms](https://github.com/aiidateam/aiida-quantumespresso/blob/main/src/aiida_quantumespresso/data/hubbard_structure.py#L186), we can provide the name of the atom, and then a set of operations are done in order to understand each atomic site which should have the same U. This cannot be done a priori and it is a bit counterintuitive on how to do it form the constructor (we pass the Hubbard class, or a dictionary then to be internally processed in order to set the instance of Hubbard?)

In my opinion, we can provide some method in the property classes that allows to instantiate one of them. This however may give a fake hint on the possiblity to mutate them once the StructureData is created. I don't really know about this, but if I think of the Hubbard property, one and very useful method is the `from_list` one.

**Comment by unkcpz** [comment]
I prefer the "built-in" method, it similar to how the current `StrutureData` and `KpointsData` is initialized. 
Moreover, I think before storing the data in the database, the objects are supposed to have full flexibility to be changed or attached with more information required. 
The "bulid-in" method requires proper definition on the "from_**" constructor methods to make it easy to use and validators that prevent user from defining things physically not valid. I find a post at https://realpython.com/python-multiple-constructors/ where shows some builtin libraries also has this pattern, worth to have a look.

**Comment by sphuber** [comment]
I would actually tend to advise _against_ allowing to mutate the state after having constructed an instance. By default, I think that the constructor should require _all_ information that is necessary to construct an instance that is complete and coherent. Of course it can then have optional arguments, which would fit the properties.

Experience over the last few years has taught that allowing to modify an instance after construction leads to confusion with users and it complicates the validation and implementation. In any case, once stored, in AiiDA the node is immutable, so all setters will start raising `ModificationNotAllowed` errors. It is only when it is not stored that these setters would be useful. But _when_ exactly are we using this step-wise defining of an instance? In code, it doesn't really provide much benefit to be able to define in multiple lines as opposed to in one go in the constructor. Then there is interactive shells where you may want to "correct" an instance if it was constructed incorrectly and it needs to be updated. But then it is just as easy to get the original construction line and correct that.

> I prefer the "built-in" method, it similar to how the current StrutureData and KpointsData is initialized.

Is that your main or only reason for prefering this approach @unkcpz ? Because those plugins are exactly an example of plugin we would like to change but can't because of backwards compatibility. I think history has shown that this approach has plenty of downsides.
